### ISSUE TITLE
Compilation errors after upgrading from 5.5.x to 6.2.0

### ISSUE THREAD

**Issue by psclrzn** [rcbyr/keen-slider#160]
I am using Keen-Slider in a plain TS environment.

Somehow, after upgrading from 5.5.x to 6.2.0, I have different compilation errors, depending on how I initialize the Slider.

If I use a string as the container like this:

 ```
 var slider = new KeenSlider("#my-keen-slider", {
   loop: true,
 });
```

I get

> Argument of type 'string' is not assignable to parameter of type 'HTMLElement'

If I use an HTMLElement like this:
      
 ```
 const slider = new KeenSlider(sliderElement, {
   loop: true,
  duration: slideSpeed * 0.875,
});
```
I get the following errors: 

>  Type 'true' is not assignable to type '(boolean | { min?: number; max?: number; }) & ((slider: KeenSliderInstance<{}, {}, "created" | "slideChanged" | "loop" | "duration" | "dragStart" | "dragEnd">) => void)'

and 
      

> Type 'number' is not assignable to type '(slider: KeenSliderInstance<{}, {}, "created" | "slideChanged" | "loop" | "duration" | "dragStart" | "dragEnd">) => void'
      
Reverting every back to 5.5 works perfectly.

**Comment by rcbyr** [comment]
Hey @psclrzn ,

do you use any Frameworks like angular? Can you please give me your tsconfig?
I released a patch for the first error. The third error is a cause due to a change in the API. The duration can be changed like so:
```
const slider = new KeenSlider(sliderElement, {
  loop: true,
  defaultAnimation: {
    duration:  slideSpeed * 0.875,
  }
});
```
For the second error, I may need the tsconfig. Couldn't reproduce it yet.

**Comment by psclrzn** [comment]
@rcbyr 
Your latest patch and the solutions you mentioned above seem to fix my issues.  Thank you. The rest is a case of not having read the API changes yet.

I am not using any framework.   But if it can help, here is a copy of my tsconfig.json:

```
{
  "compilerOptions": {
    "target": "es2020",
    "module": "commonjs",
    "declaration": false,
    "removeComments": true,
    "noLib": false,
    "experimentalDecorators": true,
    "sourceMap": true,
    "pretty": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitUseStrict": false,
    "noFallthroughCasesInSwitch": true,
    "allowJs": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node",
    "suppressImplicitAnyIndexErrors": true,
    "allowSyntheticDefaultImports" : true,
    "esModuleInterop" : true,
    "lib": ["es2015.collection","es2015.core","es5","es2015.promise","dom"],
    "types": [

    ],
    "baseUrl" : "./",
    "paths": {
      "*": [
          "node_modules/*",
          "types/*",
          "node_modules/@types/*"
      ]
  }
  },
  "include": [ "Scripts/**/*", "types/*" ],
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false
}
```

It's a .NET 5 MVC Web App (with Umbraco 9) and some JS (TS Compiled) on the side for good measure.

**Comment by rcbyr** [comment]
Hey @psclrzn 

I fixed the type problem with the latest version (v6.3.3). Thanks for the hint.
